# Generated by Django 4.1.4 on 2022-12-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_chat_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustommodel',
            name='username',
        ),
    ]
