# Generated by Django 4.1.4 on 2022-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_mycustommodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustommodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mycustommodel',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], max_length=10),
        ),
    ]
