# Generated by Django 4.1.4 on 2022-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to='picture'),
        ),
    ]
